# Generated by Django 4.0.1 on 2022-01-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
    ]
